// <auto-generated />
namespace StackedDeck.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20160328 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20160328));
        
        string IMigrationMetadata.Id
        {
            get { return "201603260649312_20160328"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
